apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  labels:
    name: monitor

spec:
  destination:
    namespace: monitor
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: kube-prometheus-stack-51.0.3
    chart: kube-prometheus-stack

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
