apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  labels:
    name: grafana

spec:
  destination:
    namespace: monitor
    server: "https://kubernetes.default.svc"
  project: default
  source:
    - repoURL: "https://charts.bitnami.com/bitnami"
      targetRevision: 9.2.1
      chart: grafana

      helm:
        valueFiles:
        - $values/system/monitor/grafana.yaml


    - repoURL: "https://github.com/Walkmana-25/argocd-cluster"
      targetRevision: main
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
