apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  labels:
    name: prometheus

spec:
  destination:
    namespace: grafana
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.1.2
    chart: grafana

    helm:
      valueFiles:
        - prometheus.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
