apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  labels:
    name: grafana

spec:
  destination:
    namespace: monitor
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    #targetRevision: 10.1.2
    chart: grafana

    helm:
      valueFiles:
        - grafana.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
