apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

  labels:
    name: prometheus

spec:
  destination:
    namespace: monitor
    server: "https://kubernetes.default.svc"
  project: default
  source:
    - repoURL: "https://charts.bitnami.com/bitnami"
      targetRevision: 8.19.0
      chart: kube-prometheus

      helm:
        valueFiles:
        - $values/system/monitor/prometheus.yaml
    - repoURL: "https://github.com/Walkmana-25/argocd-cluster"
      targetRevision: main
      ref: values

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
